// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

/**
 * <pre>
 * The container for all component parts of the area sub-element of the
 * info sub-element of the alert message.
 * </pre>
 *
 * Protobuf type {@code publicalerts.cap.Area}
 */
public final class Area extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:publicalerts.cap.Area)
    AreaOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      Area.class.getName());
  }
  // Use Area.newBuilder() to construct.
  private Area(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Area() {
    areaDesc_ = "";
    polygon_ = java.util.Collections.emptyList();
    circle_ = java.util.Collections.emptyList();
    geocode_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Area_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Area_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.publicalerts.cap.Area.class, com.google.publicalerts.cap.Area.Builder.class);
  }

  private int bitField0_;
  public static final int AREA_DESC_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object areaDesc_ = "";
  /**
   * <pre>
   * A text description of the affected area.
   * </pre>
   *
   * <code>required string area_desc = 1;</code>
   * @return Whether the areaDesc field is set.
   */
  @java.lang.Override
  public boolean hasAreaDesc() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * A text description of the affected area.
   * </pre>
   *
   * <code>required string area_desc = 1;</code>
   * @return The areaDesc.
   */
  @java.lang.Override
  public java.lang.String getAreaDesc() {
    java.lang.Object ref = areaDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        areaDesc_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * A text description of the affected area.
   * </pre>
   *
   * <code>required string area_desc = 1;</code>
   * @return The bytes for areaDesc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAreaDescBytes() {
    java.lang.Object ref = areaDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POLYGON_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.publicalerts.cap.Polygon> polygon_;
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.publicalerts.cap.Polygon> getPolygonList() {
    return polygon_;
  }
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.publicalerts.cap.PolygonOrBuilder> 
      getPolygonOrBuilderList() {
    return polygon_;
  }
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
   */
  @java.lang.Override
  public int getPolygonCount() {
    return polygon_.size();
  }
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.Polygon getPolygon(int index) {
    return polygon_.get(index);
  }
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.PolygonOrBuilder getPolygonOrBuilder(
      int index) {
    return polygon_.get(index);
  }

  public static final int CIRCLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.google.publicalerts.cap.Circle> circle_;
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.publicalerts.cap.Circle> getCircleList() {
    return circle_;
  }
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.publicalerts.cap.CircleOrBuilder> 
      getCircleOrBuilderList() {
    return circle_;
  }
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
   */
  @java.lang.Override
  public int getCircleCount() {
    return circle_.size();
  }
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.Circle getCircle(int index) {
    return circle_.get(index);
  }
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.CircleOrBuilder getCircleOrBuilder(
      int index) {
    return circle_.get(index);
  }

  public static final int GEOCODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.publicalerts.cap.ValuePair> geocode_;
  /**
   * <pre>
   * The geographic code delineating the affected area of the alert message,
   * where the content of ?valueName? is a user-assigned string designating
   * the domain of the code, and the content of ?value? is a string (which
   * may represent a number) denoting the value itself
   * (e.g., valueName="SAME" and value="006113").
   * This element is primarily for compatibility with other systems. Use of
   * this element presumes knowledge of the coding system on the part of
   * recipients; therefore, for interoperability, it SHOULD be used in
   * concert with an equivalent description in the more universally understood
   * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.publicalerts.cap.ValuePair> getGeocodeList() {
    return geocode_;
  }
  /**
   * <pre>
   * The geographic code delineating the affected area of the alert message,
   * where the content of ?valueName? is a user-assigned string designating
   * the domain of the code, and the content of ?value? is a string (which
   * may represent a number) denoting the value itself
   * (e.g., valueName="SAME" and value="006113").
   * This element is primarily for compatibility with other systems. Use of
   * this element presumes knowledge of the coding system on the part of
   * recipients; therefore, for interoperability, it SHOULD be used in
   * concert with an equivalent description in the more universally understood
   * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.publicalerts.cap.ValuePairOrBuilder> 
      getGeocodeOrBuilderList() {
    return geocode_;
  }
  /**
   * <pre>
   * The geographic code delineating the affected area of the alert message,
   * where the content of ?valueName? is a user-assigned string designating
   * the domain of the code, and the content of ?value? is a string (which
   * may represent a number) denoting the value itself
   * (e.g., valueName="SAME" and value="006113").
   * This element is primarily for compatibility with other systems. Use of
   * this element presumes knowledge of the coding system on the part of
   * recipients; therefore, for interoperability, it SHOULD be used in
   * concert with an equivalent description in the more universally understood
   * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
   */
  @java.lang.Override
  public int getGeocodeCount() {
    return geocode_.size();
  }
  /**
   * <pre>
   * The geographic code delineating the affected area of the alert message,
   * where the content of ?valueName? is a user-assigned string designating
   * the domain of the code, and the content of ?value? is a string (which
   * may represent a number) denoting the value itself
   * (e.g., valueName="SAME" and value="006113").
   * This element is primarily for compatibility with other systems. Use of
   * this element presumes knowledge of the coding system on the part of
   * recipients; therefore, for interoperability, it SHOULD be used in
   * concert with an equivalent description in the more universally understood
   * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.ValuePair getGeocode(int index) {
    return geocode_.get(index);
  }
  /**
   * <pre>
   * The geographic code delineating the affected area of the alert message,
   * where the content of ?valueName? is a user-assigned string designating
   * the domain of the code, and the content of ?value? is a string (which
   * may represent a number) denoting the value itself
   * (e.g., valueName="SAME" and value="006113").
   * This element is primarily for compatibility with other systems. Use of
   * this element presumes knowledge of the coding system on the part of
   * recipients; therefore, for interoperability, it SHOULD be used in
   * concert with an equivalent description in the more universally understood
   * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
   * </pre>
   *
   * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.ValuePairOrBuilder getGeocodeOrBuilder(
      int index) {
    return geocode_.get(index);
  }

  public static final int ALTITUDE_FIELD_NUMBER = 5;
  private double altitude_ = 0D;
  /**
   * <pre>
   * The specific or minimum altitude of the affected area of the alert
   * message. If used with the &lt;ceiling&gt; element this value is the lower limit
   * of a range. Otherwise, this value specifies a specific altitude.
   * The altitude measure is in feet above mean sea level per the [WGS-84]
   * datum.
   * </pre>
   *
   * <code>optional double altitude = 5;</code>
   * @return Whether the altitude field is set.
   */
  @java.lang.Override
  public boolean hasAltitude() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The specific or minimum altitude of the affected area of the alert
   * message. If used with the &lt;ceiling&gt; element this value is the lower limit
   * of a range. Otherwise, this value specifies a specific altitude.
   * The altitude measure is in feet above mean sea level per the [WGS-84]
   * datum.
   * </pre>
   *
   * <code>optional double altitude = 5;</code>
   * @return The altitude.
   */
  @java.lang.Override
  public double getAltitude() {
    return altitude_;
  }

  public static final int CEILING_FIELD_NUMBER = 6;
  private double ceiling_ = 0D;
  /**
   * <pre>
   * The maximum altitude of the affected area of the alert message.
   * MUST NOT be used except in combination with the &lt;altitude&gt; element.
   * The ceiling measure is in feet above mean sea level per the [WGS-84]
   * datum.
   * </pre>
   *
   * <code>optional double ceiling = 6;</code>
   * @return Whether the ceiling field is set.
   */
  @java.lang.Override
  public boolean hasCeiling() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The maximum altitude of the affected area of the alert message.
   * MUST NOT be used except in combination with the &lt;altitude&gt; element.
   * The ceiling measure is in feet above mean sea level per the [WGS-84]
   * datum.
   * </pre>
   *
   * <code>optional double ceiling = 6;</code>
   * @return The ceiling.
   */
  @java.lang.Override
  public double getCeiling() {
    return ceiling_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasAreaDesc()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getPolygonCount(); i++) {
      if (!getPolygon(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getCircleCount(); i++) {
      if (!getCircle(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getGeocodeCount(); i++) {
      if (!getGeocode(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, areaDesc_);
    }
    for (int i = 0; i < polygon_.size(); i++) {
      output.writeMessage(2, polygon_.get(i));
    }
    for (int i = 0; i < circle_.size(); i++) {
      output.writeMessage(3, circle_.get(i));
    }
    for (int i = 0; i < geocode_.size(); i++) {
      output.writeMessage(4, geocode_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(5, altitude_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(6, ceiling_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, areaDesc_);
    }
    for (int i = 0; i < polygon_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, polygon_.get(i));
    }
    for (int i = 0; i < circle_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, circle_.get(i));
    }
    for (int i = 0; i < geocode_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, geocode_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, altitude_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, ceiling_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.publicalerts.cap.Area)) {
      return super.equals(obj);
    }
    com.google.publicalerts.cap.Area other = (com.google.publicalerts.cap.Area) obj;

    if (hasAreaDesc() != other.hasAreaDesc()) return false;
    if (hasAreaDesc()) {
      if (!getAreaDesc()
          .equals(other.getAreaDesc())) return false;
    }
    if (!getPolygonList()
        .equals(other.getPolygonList())) return false;
    if (!getCircleList()
        .equals(other.getCircleList())) return false;
    if (!getGeocodeList()
        .equals(other.getGeocodeList())) return false;
    if (hasAltitude() != other.hasAltitude()) return false;
    if (hasAltitude()) {
      if (java.lang.Double.doubleToLongBits(getAltitude())
          != java.lang.Double.doubleToLongBits(
              other.getAltitude())) return false;
    }
    if (hasCeiling() != other.hasCeiling()) return false;
    if (hasCeiling()) {
      if (java.lang.Double.doubleToLongBits(getCeiling())
          != java.lang.Double.doubleToLongBits(
              other.getCeiling())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAreaDesc()) {
      hash = (37 * hash) + AREA_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getAreaDesc().hashCode();
    }
    if (getPolygonCount() > 0) {
      hash = (37 * hash) + POLYGON_FIELD_NUMBER;
      hash = (53 * hash) + getPolygonList().hashCode();
    }
    if (getCircleCount() > 0) {
      hash = (37 * hash) + CIRCLE_FIELD_NUMBER;
      hash = (53 * hash) + getCircleList().hashCode();
    }
    if (getGeocodeCount() > 0) {
      hash = (37 * hash) + GEOCODE_FIELD_NUMBER;
      hash = (53 * hash) + getGeocodeList().hashCode();
    }
    if (hasAltitude()) {
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAltitude()));
    }
    if (hasCeiling()) {
      hash = (37 * hash) + CEILING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCeiling()));
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.publicalerts.cap.Area parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Area parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Area parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.publicalerts.cap.Area parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.publicalerts.cap.Area parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Area parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.publicalerts.cap.Area prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The container for all component parts of the area sub-element of the
   * info sub-element of the alert message.
   * </pre>
   *
   * Protobuf type {@code publicalerts.cap.Area}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:publicalerts.cap.Area)
      com.google.publicalerts.cap.AreaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Area_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Area_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.publicalerts.cap.Area.class, com.google.publicalerts.cap.Area.Builder.class);
    }

    // Construct using com.google.publicalerts.cap.Area.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      areaDesc_ = "";
      if (polygonBuilder_ == null) {
        polygon_ = java.util.Collections.emptyList();
      } else {
        polygon_ = null;
        polygonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (circleBuilder_ == null) {
        circle_ = java.util.Collections.emptyList();
      } else {
        circle_ = null;
        circleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (geocodeBuilder_ == null) {
        geocode_ = java.util.Collections.emptyList();
      } else {
        geocode_ = null;
        geocodeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      altitude_ = 0D;
      ceiling_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Area_descriptor;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Area getDefaultInstanceForType() {
      return com.google.publicalerts.cap.Area.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Area build() {
      com.google.publicalerts.cap.Area result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Area buildPartial() {
      com.google.publicalerts.cap.Area result = new com.google.publicalerts.cap.Area(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.publicalerts.cap.Area result) {
      if (polygonBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          polygon_ = java.util.Collections.unmodifiableList(polygon_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.polygon_ = polygon_;
      } else {
        result.polygon_ = polygonBuilder_.build();
      }
      if (circleBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          circle_ = java.util.Collections.unmodifiableList(circle_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.circle_ = circle_;
      } else {
        result.circle_ = circleBuilder_.build();
      }
      if (geocodeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          geocode_ = java.util.Collections.unmodifiableList(geocode_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.geocode_ = geocode_;
      } else {
        result.geocode_ = geocodeBuilder_.build();
      }
    }

    private void buildPartial0(com.google.publicalerts.cap.Area result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.areaDesc_ = areaDesc_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.altitude_ = altitude_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.ceiling_ = ceiling_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.publicalerts.cap.Area) {
        return mergeFrom((com.google.publicalerts.cap.Area)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.publicalerts.cap.Area other) {
      if (other == com.google.publicalerts.cap.Area.getDefaultInstance()) return this;
      if (other.hasAreaDesc()) {
        areaDesc_ = other.areaDesc_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (polygonBuilder_ == null) {
        if (!other.polygon_.isEmpty()) {
          if (polygon_.isEmpty()) {
            polygon_ = other.polygon_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePolygonIsMutable();
            polygon_.addAll(other.polygon_);
          }
          onChanged();
        }
      } else {
        if (!other.polygon_.isEmpty()) {
          if (polygonBuilder_.isEmpty()) {
            polygonBuilder_.dispose();
            polygonBuilder_ = null;
            polygon_ = other.polygon_;
            bitField0_ = (bitField0_ & ~0x00000002);
            polygonBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPolygonFieldBuilder() : null;
          } else {
            polygonBuilder_.addAllMessages(other.polygon_);
          }
        }
      }
      if (circleBuilder_ == null) {
        if (!other.circle_.isEmpty()) {
          if (circle_.isEmpty()) {
            circle_ = other.circle_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCircleIsMutable();
            circle_.addAll(other.circle_);
          }
          onChanged();
        }
      } else {
        if (!other.circle_.isEmpty()) {
          if (circleBuilder_.isEmpty()) {
            circleBuilder_.dispose();
            circleBuilder_ = null;
            circle_ = other.circle_;
            bitField0_ = (bitField0_ & ~0x00000004);
            circleBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCircleFieldBuilder() : null;
          } else {
            circleBuilder_.addAllMessages(other.circle_);
          }
        }
      }
      if (geocodeBuilder_ == null) {
        if (!other.geocode_.isEmpty()) {
          if (geocode_.isEmpty()) {
            geocode_ = other.geocode_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGeocodeIsMutable();
            geocode_.addAll(other.geocode_);
          }
          onChanged();
        }
      } else {
        if (!other.geocode_.isEmpty()) {
          if (geocodeBuilder_.isEmpty()) {
            geocodeBuilder_.dispose();
            geocodeBuilder_ = null;
            geocode_ = other.geocode_;
            bitField0_ = (bitField0_ & ~0x00000008);
            geocodeBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGeocodeFieldBuilder() : null;
          } else {
            geocodeBuilder_.addAllMessages(other.geocode_);
          }
        }
      }
      if (other.hasAltitude()) {
        setAltitude(other.getAltitude());
      }
      if (other.hasCeiling()) {
        setCeiling(other.getCeiling());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasAreaDesc()) {
        return false;
      }
      for (int i = 0; i < getPolygonCount(); i++) {
        if (!getPolygon(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getCircleCount(); i++) {
        if (!getCircle(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getGeocodeCount(); i++) {
        if (!getGeocode(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              areaDesc_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.publicalerts.cap.Polygon m =
                  input.readMessage(
                      com.google.publicalerts.cap.Polygon.parser(),
                      extensionRegistry);
              if (polygonBuilder_ == null) {
                ensurePolygonIsMutable();
                polygon_.add(m);
              } else {
                polygonBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.google.publicalerts.cap.Circle m =
                  input.readMessage(
                      com.google.publicalerts.cap.Circle.parser(),
                      extensionRegistry);
              if (circleBuilder_ == null) {
                ensureCircleIsMutable();
                circle_.add(m);
              } else {
                circleBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.google.publicalerts.cap.ValuePair m =
                  input.readMessage(
                      com.google.publicalerts.cap.ValuePair.parser(),
                      extensionRegistry);
              if (geocodeBuilder_ == null) {
                ensureGeocodeIsMutable();
                geocode_.add(m);
              } else {
                geocodeBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 41: {
              altitude_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              ceiling_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object areaDesc_ = "";
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @return Whether the areaDesc field is set.
     */
    public boolean hasAreaDesc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @return The areaDesc.
     */
    public java.lang.String getAreaDesc() {
      java.lang.Object ref = areaDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          areaDesc_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @return The bytes for areaDesc.
     */
    public com.google.protobuf.ByteString
        getAreaDescBytes() {
      java.lang.Object ref = areaDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @param value The areaDesc to set.
     * @return This builder for chaining.
     */
    public Builder setAreaDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      areaDesc_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAreaDesc() {
      areaDesc_ = getDefaultInstance().getAreaDesc();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A text description of the affected area.
     * </pre>
     *
     * <code>required string area_desc = 1;</code>
     * @param value The bytes for areaDesc to set.
     * @return This builder for chaining.
     */
    public Builder setAreaDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      areaDesc_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.publicalerts.cap.Polygon> polygon_ =
      java.util.Collections.emptyList();
    private void ensurePolygonIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        polygon_ = new java.util.ArrayList<com.google.publicalerts.cap.Polygon>(polygon_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Polygon, com.google.publicalerts.cap.Polygon.Builder, com.google.publicalerts.cap.PolygonOrBuilder> polygonBuilder_;

    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Polygon> getPolygonList() {
      if (polygonBuilder_ == null) {
        return java.util.Collections.unmodifiableList(polygon_);
      } else {
        return polygonBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public int getPolygonCount() {
      if (polygonBuilder_ == null) {
        return polygon_.size();
      } else {
        return polygonBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public com.google.publicalerts.cap.Polygon getPolygon(int index) {
      if (polygonBuilder_ == null) {
        return polygon_.get(index);
      } else {
        return polygonBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder setPolygon(
        int index, com.google.publicalerts.cap.Polygon value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.set(index, value);
        onChanged();
      } else {
        polygonBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder setPolygon(
        int index, com.google.publicalerts.cap.Polygon.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.set(index, builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder addPolygon(com.google.publicalerts.cap.Polygon value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.add(value);
        onChanged();
      } else {
        polygonBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder addPolygon(
        int index, com.google.publicalerts.cap.Polygon value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.add(index, value);
        onChanged();
      } else {
        polygonBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder addPolygon(
        com.google.publicalerts.cap.Polygon.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.add(builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder addPolygon(
        int index, com.google.publicalerts.cap.Polygon.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.add(index, builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder addAllPolygon(
        java.lang.Iterable<? extends com.google.publicalerts.cap.Polygon> values) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, polygon_);
        onChanged();
      } else {
        polygonBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder clearPolygon() {
      if (polygonBuilder_ == null) {
        polygon_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        polygonBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public Builder removePolygon(int index) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.remove(index);
        onChanged();
      } else {
        polygonBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public com.google.publicalerts.cap.Polygon.Builder getPolygonBuilder(
        int index) {
      return getPolygonFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public com.google.publicalerts.cap.PolygonOrBuilder getPolygonOrBuilder(
        int index) {
      if (polygonBuilder_ == null) {
        return polygon_.get(index);  } else {
        return polygonBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public java.util.List<? extends com.google.publicalerts.cap.PolygonOrBuilder> 
         getPolygonOrBuilderList() {
      if (polygonBuilder_ != null) {
        return polygonBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(polygon_);
      }
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public com.google.publicalerts.cap.Polygon.Builder addPolygonBuilder() {
      return getPolygonFieldBuilder().addBuilder(
          com.google.publicalerts.cap.Polygon.getDefaultInstance());
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public com.google.publicalerts.cap.Polygon.Builder addPolygonBuilder(
        int index) {
      return getPolygonFieldBuilder().addBuilder(
          index, com.google.publicalerts.cap.Polygon.getDefaultInstance());
    }
    /**
     * <pre>
     * The paired values of points defining a polygon that delineates the affected
     * area of the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Polygon polygon = 2;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Polygon.Builder> 
         getPolygonBuilderList() {
      return getPolygonFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Polygon, com.google.publicalerts.cap.Polygon.Builder, com.google.publicalerts.cap.PolygonOrBuilder> 
        getPolygonFieldBuilder() {
      if (polygonBuilder_ == null) {
        polygonBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.publicalerts.cap.Polygon, com.google.publicalerts.cap.Polygon.Builder, com.google.publicalerts.cap.PolygonOrBuilder>(
                polygon_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        polygon_ = null;
      }
      return polygonBuilder_;
    }

    private java.util.List<com.google.publicalerts.cap.Circle> circle_ =
      java.util.Collections.emptyList();
    private void ensureCircleIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        circle_ = new java.util.ArrayList<com.google.publicalerts.cap.Circle>(circle_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Circle, com.google.publicalerts.cap.Circle.Builder, com.google.publicalerts.cap.CircleOrBuilder> circleBuilder_;

    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Circle> getCircleList() {
      if (circleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(circle_);
      } else {
        return circleBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public int getCircleCount() {
      if (circleBuilder_ == null) {
        return circle_.size();
      } else {
        return circleBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public com.google.publicalerts.cap.Circle getCircle(int index) {
      if (circleBuilder_ == null) {
        return circle_.get(index);
      } else {
        return circleBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder setCircle(
        int index, com.google.publicalerts.cap.Circle value) {
      if (circleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCircleIsMutable();
        circle_.set(index, value);
        onChanged();
      } else {
        circleBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder setCircle(
        int index, com.google.publicalerts.cap.Circle.Builder builderForValue) {
      if (circleBuilder_ == null) {
        ensureCircleIsMutable();
        circle_.set(index, builderForValue.build());
        onChanged();
      } else {
        circleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder addCircle(com.google.publicalerts.cap.Circle value) {
      if (circleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCircleIsMutable();
        circle_.add(value);
        onChanged();
      } else {
        circleBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder addCircle(
        int index, com.google.publicalerts.cap.Circle value) {
      if (circleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCircleIsMutable();
        circle_.add(index, value);
        onChanged();
      } else {
        circleBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder addCircle(
        com.google.publicalerts.cap.Circle.Builder builderForValue) {
      if (circleBuilder_ == null) {
        ensureCircleIsMutable();
        circle_.add(builderForValue.build());
        onChanged();
      } else {
        circleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder addCircle(
        int index, com.google.publicalerts.cap.Circle.Builder builderForValue) {
      if (circleBuilder_ == null) {
        ensureCircleIsMutable();
        circle_.add(index, builderForValue.build());
        onChanged();
      } else {
        circleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder addAllCircle(
        java.lang.Iterable<? extends com.google.publicalerts.cap.Circle> values) {
      if (circleBuilder_ == null) {
        ensureCircleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, circle_);
        onChanged();
      } else {
        circleBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder clearCircle() {
      if (circleBuilder_ == null) {
        circle_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        circleBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public Builder removeCircle(int index) {
      if (circleBuilder_ == null) {
        ensureCircleIsMutable();
        circle_.remove(index);
        onChanged();
      } else {
        circleBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public com.google.publicalerts.cap.Circle.Builder getCircleBuilder(
        int index) {
      return getCircleFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public com.google.publicalerts.cap.CircleOrBuilder getCircleOrBuilder(
        int index) {
      if (circleBuilder_ == null) {
        return circle_.get(index);  } else {
        return circleBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public java.util.List<? extends com.google.publicalerts.cap.CircleOrBuilder> 
         getCircleOrBuilderList() {
      if (circleBuilder_ != null) {
        return circleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(circle_);
      }
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public com.google.publicalerts.cap.Circle.Builder addCircleBuilder() {
      return getCircleFieldBuilder().addBuilder(
          com.google.publicalerts.cap.Circle.getDefaultInstance());
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public com.google.publicalerts.cap.Circle.Builder addCircleBuilder(
        int index) {
      return getCircleFieldBuilder().addBuilder(
          index, com.google.publicalerts.cap.Circle.getDefaultInstance());
    }
    /**
     * <pre>
     * The paired values of a point and radius delineating the affected area of
     * the alert message.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.Circle circle = 3;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Circle.Builder> 
         getCircleBuilderList() {
      return getCircleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Circle, com.google.publicalerts.cap.Circle.Builder, com.google.publicalerts.cap.CircleOrBuilder> 
        getCircleFieldBuilder() {
      if (circleBuilder_ == null) {
        circleBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.publicalerts.cap.Circle, com.google.publicalerts.cap.Circle.Builder, com.google.publicalerts.cap.CircleOrBuilder>(
                circle_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        circle_ = null;
      }
      return circleBuilder_;
    }

    private java.util.List<com.google.publicalerts.cap.ValuePair> geocode_ =
      java.util.Collections.emptyList();
    private void ensureGeocodeIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        geocode_ = new java.util.ArrayList<com.google.publicalerts.cap.ValuePair>(geocode_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.ValuePair, com.google.publicalerts.cap.ValuePair.Builder, com.google.publicalerts.cap.ValuePairOrBuilder> geocodeBuilder_;

    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public java.util.List<com.google.publicalerts.cap.ValuePair> getGeocodeList() {
      if (geocodeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(geocode_);
      } else {
        return geocodeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public int getGeocodeCount() {
      if (geocodeBuilder_ == null) {
        return geocode_.size();
      } else {
        return geocodeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public com.google.publicalerts.cap.ValuePair getGeocode(int index) {
      if (geocodeBuilder_ == null) {
        return geocode_.get(index);
      } else {
        return geocodeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder setGeocode(
        int index, com.google.publicalerts.cap.ValuePair value) {
      if (geocodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeocodeIsMutable();
        geocode_.set(index, value);
        onChanged();
      } else {
        geocodeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder setGeocode(
        int index, com.google.publicalerts.cap.ValuePair.Builder builderForValue) {
      if (geocodeBuilder_ == null) {
        ensureGeocodeIsMutable();
        geocode_.set(index, builderForValue.build());
        onChanged();
      } else {
        geocodeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder addGeocode(com.google.publicalerts.cap.ValuePair value) {
      if (geocodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeocodeIsMutable();
        geocode_.add(value);
        onChanged();
      } else {
        geocodeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder addGeocode(
        int index, com.google.publicalerts.cap.ValuePair value) {
      if (geocodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGeocodeIsMutable();
        geocode_.add(index, value);
        onChanged();
      } else {
        geocodeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder addGeocode(
        com.google.publicalerts.cap.ValuePair.Builder builderForValue) {
      if (geocodeBuilder_ == null) {
        ensureGeocodeIsMutable();
        geocode_.add(builderForValue.build());
        onChanged();
      } else {
        geocodeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder addGeocode(
        int index, com.google.publicalerts.cap.ValuePair.Builder builderForValue) {
      if (geocodeBuilder_ == null) {
        ensureGeocodeIsMutable();
        geocode_.add(index, builderForValue.build());
        onChanged();
      } else {
        geocodeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder addAllGeocode(
        java.lang.Iterable<? extends com.google.publicalerts.cap.ValuePair> values) {
      if (geocodeBuilder_ == null) {
        ensureGeocodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, geocode_);
        onChanged();
      } else {
        geocodeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder clearGeocode() {
      if (geocodeBuilder_ == null) {
        geocode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        geocodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public Builder removeGeocode(int index) {
      if (geocodeBuilder_ == null) {
        ensureGeocodeIsMutable();
        geocode_.remove(index);
        onChanged();
      } else {
        geocodeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public com.google.publicalerts.cap.ValuePair.Builder getGeocodeBuilder(
        int index) {
      return getGeocodeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public com.google.publicalerts.cap.ValuePairOrBuilder getGeocodeOrBuilder(
        int index) {
      if (geocodeBuilder_ == null) {
        return geocode_.get(index);  } else {
        return geocodeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public java.util.List<? extends com.google.publicalerts.cap.ValuePairOrBuilder> 
         getGeocodeOrBuilderList() {
      if (geocodeBuilder_ != null) {
        return geocodeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(geocode_);
      }
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public com.google.publicalerts.cap.ValuePair.Builder addGeocodeBuilder() {
      return getGeocodeFieldBuilder().addBuilder(
          com.google.publicalerts.cap.ValuePair.getDefaultInstance());
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public com.google.publicalerts.cap.ValuePair.Builder addGeocodeBuilder(
        int index) {
      return getGeocodeFieldBuilder().addBuilder(
          index, com.google.publicalerts.cap.ValuePair.getDefaultInstance());
    }
    /**
     * <pre>
     * The geographic code delineating the affected area of the alert message,
     * where the content of ?valueName? is a user-assigned string designating
     * the domain of the code, and the content of ?value? is a string (which
     * may represent a number) denoting the value itself
     * (e.g., valueName="SAME" and value="006113").
     * This element is primarily for compatibility with other systems. Use of
     * this element presumes knowledge of the coding system on the part of
     * recipients; therefore, for interoperability, it SHOULD be used in
     * concert with an equivalent description in the more universally understood
     * &lt;polygon&gt; and &lt;circle&gt; forms whenever possible.
     * </pre>
     *
     * <code>repeated .publicalerts.cap.ValuePair geocode = 4;</code>
     */
    public java.util.List<com.google.publicalerts.cap.ValuePair.Builder> 
         getGeocodeBuilderList() {
      return getGeocodeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.ValuePair, com.google.publicalerts.cap.ValuePair.Builder, com.google.publicalerts.cap.ValuePairOrBuilder> 
        getGeocodeFieldBuilder() {
      if (geocodeBuilder_ == null) {
        geocodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.publicalerts.cap.ValuePair, com.google.publicalerts.cap.ValuePair.Builder, com.google.publicalerts.cap.ValuePairOrBuilder>(
                geocode_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        geocode_ = null;
      }
      return geocodeBuilder_;
    }

    private double altitude_ ;
    /**
     * <pre>
     * The specific or minimum altitude of the affected area of the alert
     * message. If used with the &lt;ceiling&gt; element this value is the lower limit
     * of a range. Otherwise, this value specifies a specific altitude.
     * The altitude measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double altitude = 5;</code>
     * @return Whether the altitude field is set.
     */
    @java.lang.Override
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The specific or minimum altitude of the affected area of the alert
     * message. If used with the &lt;ceiling&gt; element this value is the lower limit
     * of a range. Otherwise, this value specifies a specific altitude.
     * The altitude measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double altitude = 5;</code>
     * @return The altitude.
     */
    @java.lang.Override
    public double getAltitude() {
      return altitude_;
    }
    /**
     * <pre>
     * The specific or minimum altitude of the affected area of the alert
     * message. If used with the &lt;ceiling&gt; element this value is the lower limit
     * of a range. Otherwise, this value specifies a specific altitude.
     * The altitude measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double altitude = 5;</code>
     * @param value The altitude to set.
     * @return This builder for chaining.
     */
    public Builder setAltitude(double value) {

      altitude_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The specific or minimum altitude of the affected area of the alert
     * message. If used with the &lt;ceiling&gt; element this value is the lower limit
     * of a range. Otherwise, this value specifies a specific altitude.
     * The altitude measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double altitude = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAltitude() {
      bitField0_ = (bitField0_ & ~0x00000010);
      altitude_ = 0D;
      onChanged();
      return this;
    }

    private double ceiling_ ;
    /**
     * <pre>
     * The maximum altitude of the affected area of the alert message.
     * MUST NOT be used except in combination with the &lt;altitude&gt; element.
     * The ceiling measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double ceiling = 6;</code>
     * @return Whether the ceiling field is set.
     */
    @java.lang.Override
    public boolean hasCeiling() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * The maximum altitude of the affected area of the alert message.
     * MUST NOT be used except in combination with the &lt;altitude&gt; element.
     * The ceiling measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double ceiling = 6;</code>
     * @return The ceiling.
     */
    @java.lang.Override
    public double getCeiling() {
      return ceiling_;
    }
    /**
     * <pre>
     * The maximum altitude of the affected area of the alert message.
     * MUST NOT be used except in combination with the &lt;altitude&gt; element.
     * The ceiling measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double ceiling = 6;</code>
     * @param value The ceiling to set.
     * @return This builder for chaining.
     */
    public Builder setCeiling(double value) {

      ceiling_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum altitude of the affected area of the alert message.
     * MUST NOT be used except in combination with the &lt;altitude&gt; element.
     * The ceiling measure is in feet above mean sea level per the [WGS-84]
     * datum.
     * </pre>
     *
     * <code>optional double ceiling = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCeiling() {
      bitField0_ = (bitField0_ & ~0x00000020);
      ceiling_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:publicalerts.cap.Area)
  }

  // @@protoc_insertion_point(class_scope:publicalerts.cap.Area)
  private static final com.google.publicalerts.cap.Area DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.publicalerts.cap.Area();
  }

  public static com.google.publicalerts.cap.Area getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Area>
      PARSER = new com.google.protobuf.AbstractParser<Area>() {
    @java.lang.Override
    public Area parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Area> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Area> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.publicalerts.cap.Area getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

