// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

public interface CircleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Circle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   * @return Whether the point field is set.
   */
  boolean hasPoint();
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   * @return The point.
   */
  com.google.publicalerts.cap.Point getPoint();
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder();

  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   * @return Whether the radius field is set.
   */
  boolean hasRadius();
  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   * @return The radius.
   */
  double getRadius();
}
