// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required double latitude = 1;</code>
   * @return Whether the latitude field is set.
   */
  boolean hasLatitude();
  /**
   * <code>required double latitude = 1;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>required double longitude = 2;</code>
   * @return Whether the longitude field is set.
   */
  boolean hasLongitude();
  /**
   * <code>required double longitude = 2;</code>
   * @return The longitude.
   */
  double getLongitude();
}
