// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

public interface PolygonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Polygon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  java.util.List<com.google.publicalerts.cap.Point> 
      getPointList();
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  com.google.publicalerts.cap.Point getPoint(int index);
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  int getPointCount();
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  java.util.List<? extends com.google.publicalerts.cap.PointOrBuilder> 
      getPointOrBuilderList();
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder(
      int index);
}
