// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

/**
 * <pre>
 * The paired values of points defining a polygon that delineates the affected
 * area of the alert message.  A minimum of 4 coordinate pairs MUST be present
 * and the first and last pairs of coordinates MUST be the same.
 * </pre>
 *
 * Protobuf type {@code publicalerts.cap.Polygon}
 */
public final class Polygon extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:publicalerts.cap.Polygon)
    PolygonOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      Polygon.class.getName());
  }
  // Use Polygon.newBuilder() to construct.
  private Polygon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Polygon() {
    point_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Polygon_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Polygon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.publicalerts.cap.Polygon.class, com.google.publicalerts.cap.Polygon.Builder.class);
  }

  public static final int POINT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.publicalerts.cap.Point> point_;
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.publicalerts.cap.Point> getPointList() {
    return point_;
  }
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.publicalerts.cap.PointOrBuilder> 
      getPointOrBuilderList() {
    return point_;
  }
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  @java.lang.Override
  public int getPointCount() {
    return point_.size();
  }
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.Point getPoint(int index) {
    return point_.get(index);
  }
  /**
   * <code>repeated .publicalerts.cap.Point point = 1;</code>
   */
  @java.lang.Override
  public com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder(
      int index) {
    return point_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getPointCount(); i++) {
      if (!getPoint(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < point_.size(); i++) {
      output.writeMessage(1, point_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < point_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, point_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.publicalerts.cap.Polygon)) {
      return super.equals(obj);
    }
    com.google.publicalerts.cap.Polygon other = (com.google.publicalerts.cap.Polygon) obj;

    if (!getPointList()
        .equals(other.getPointList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPointCount() > 0) {
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPointList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.publicalerts.cap.Polygon parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.publicalerts.cap.Polygon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.publicalerts.cap.Polygon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Polygon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.publicalerts.cap.Polygon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The paired values of points defining a polygon that delineates the affected
   * area of the alert message.  A minimum of 4 coordinate pairs MUST be present
   * and the first and last pairs of coordinates MUST be the same.
   * </pre>
   *
   * Protobuf type {@code publicalerts.cap.Polygon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:publicalerts.cap.Polygon)
      com.google.publicalerts.cap.PolygonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Polygon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Polygon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.publicalerts.cap.Polygon.class, com.google.publicalerts.cap.Polygon.Builder.class);
    }

    // Construct using com.google.publicalerts.cap.Polygon.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pointBuilder_ == null) {
        point_ = java.util.Collections.emptyList();
      } else {
        point_ = null;
        pointBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Polygon_descriptor;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Polygon getDefaultInstanceForType() {
      return com.google.publicalerts.cap.Polygon.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Polygon build() {
      com.google.publicalerts.cap.Polygon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Polygon buildPartial() {
      com.google.publicalerts.cap.Polygon result = new com.google.publicalerts.cap.Polygon(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.publicalerts.cap.Polygon result) {
      if (pointBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          point_ = java.util.Collections.unmodifiableList(point_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
    }

    private void buildPartial0(com.google.publicalerts.cap.Polygon result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.publicalerts.cap.Polygon) {
        return mergeFrom((com.google.publicalerts.cap.Polygon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.publicalerts.cap.Polygon other) {
      if (other == com.google.publicalerts.cap.Polygon.getDefaultInstance()) return this;
      if (pointBuilder_ == null) {
        if (!other.point_.isEmpty()) {
          if (point_.isEmpty()) {
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointIsMutable();
            point_.addAll(other.point_);
          }
          onChanged();
        }
      } else {
        if (!other.point_.isEmpty()) {
          if (pointBuilder_.isEmpty()) {
            pointBuilder_.dispose();
            pointBuilder_ = null;
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pointBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPointFieldBuilder() : null;
          } else {
            pointBuilder_.addAllMessages(other.point_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.publicalerts.cap.Point m =
                  input.readMessage(
                      com.google.publicalerts.cap.Point.parser(),
                      extensionRegistry);
              if (pointBuilder_ == null) {
                ensurePointIsMutable();
                point_.add(m);
              } else {
                pointBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.publicalerts.cap.Point> point_ =
      java.util.Collections.emptyList();
    private void ensurePointIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        point_ = new java.util.ArrayList<com.google.publicalerts.cap.Point>(point_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder> pointBuilder_;

    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Point> getPointList() {
      if (pointBuilder_ == null) {
        return java.util.Collections.unmodifiableList(point_);
      } else {
        return pointBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public int getPointCount() {
      if (pointBuilder_ == null) {
        return point_.size();
      } else {
        return pointBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point getPoint(int index) {
      if (pointBuilder_ == null) {
        return point_.get(index);
      } else {
        return pointBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder setPoint(
        int index, com.google.publicalerts.cap.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.set(index, value);
        onChanged();
      } else {
        pointBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder setPoint(
        int index, com.google.publicalerts.cap.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.set(index, builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder addPoint(com.google.publicalerts.cap.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(value);
        onChanged();
      } else {
        pointBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder addPoint(
        int index, com.google.publicalerts.cap.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(index, value);
        onChanged();
      } else {
        pointBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder addPoint(
        com.google.publicalerts.cap.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.add(builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder addPoint(
        int index, com.google.publicalerts.cap.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.add(index, builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder addAllPoint(
        java.lang.Iterable<? extends com.google.publicalerts.cap.Point> values) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, point_);
        onChanged();
      } else {
        pointBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pointBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public Builder removePoint(int index) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.remove(index);
        onChanged();
      } else {
        pointBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point.Builder getPointBuilder(
        int index) {
      return getPointFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder(
        int index) {
      if (pointBuilder_ == null) {
        return point_.get(index);  } else {
        return pointBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public java.util.List<? extends com.google.publicalerts.cap.PointOrBuilder> 
         getPointOrBuilderList() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(point_);
      }
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point.Builder addPointBuilder() {
      return getPointFieldBuilder().addBuilder(
          com.google.publicalerts.cap.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point.Builder addPointBuilder(
        int index) {
      return getPointFieldBuilder().addBuilder(
          index, com.google.publicalerts.cap.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .publicalerts.cap.Point point = 1;</code>
     */
    public java.util.List<com.google.publicalerts.cap.Point.Builder> 
         getPointBuilderList() {
      return getPointFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder>(
                point_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:publicalerts.cap.Polygon)
  }

  // @@protoc_insertion_point(class_scope:publicalerts.cap.Polygon)
  private static final com.google.publicalerts.cap.Polygon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.publicalerts.cap.Polygon();
  }

  public static com.google.publicalerts.cap.Polygon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Polygon>
      PARSER = new com.google.protobuf.AbstractParser<Polygon>() {
    @java.lang.Override
    public Polygon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Polygon> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Polygon> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.publicalerts.cap.Polygon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

