// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cap.proto
// Protobuf Java Version: 4.28.1

package com.google.publicalerts.cap;

public interface ValuePairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.ValuePair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string value_name = 1;</code>
   * @return Whether the valueName field is set.
   */
  boolean hasValueName();
  /**
   * <code>required string value_name = 1;</code>
   * @return The valueName.
   */
  java.lang.String getValueName();
  /**
   * <code>required string value_name = 1;</code>
   * @return The bytes for valueName.
   */
  com.google.protobuf.ByteString
      getValueNameBytes();

  /**
   * <code>required string value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>required string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
